export const config = {
    canvas: document.getElementById("gameCanvas"),
    width: 640,
    height: 360,
    scale: 2,
    background: [0, 0, 0],
    stretch: false,
    letterbox: false,
    debug: true,
    debugKey: "9",
    font: "monospace",
    pixelDensity: 1,
    crisp: true,
    texFilter: "nearest",
    logMax: 6,
    hashGridSize: 64,
    global: false,
};
